/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ProtoIndexRouteImport } from './pages/proto.index'
import { Route as ProtoSlugRouteImport } from './pages/proto.$slug'
import { Route as SpikeARouteImport } from './pages/spike.a'
import { Route as SpikeBRouteImport } from './pages/spike.b'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoIndexRoute = ProtoIndexRouteImport.update({
  id: '/proto/',
  path: '/proto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoSlugRoute = ProtoSlugRouteImport.update({
  id: '/proto/$slug',
  path: '/proto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeARoute = SpikeARouteImport.update({
  id: '/spike/a',
  path: '/spike/a',
  getParentRoute: () => rootRouteImport,
} as any)
const SpikeBRoute = SpikeBRouteImport.update({
  id: '/spike/b',
  path: '/spike/b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proto/$slug': typeof ProtoSlugRoute
  '/spike/a': typeof SpikeARoute
  '/spike/b': typeof SpikeBRoute
  '/proto/': typeof ProtoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proto/$slug': typeof ProtoSlugRoute
  '/spike/a': typeof SpikeARoute
  '/spike/b': typeof SpikeBRoute
  '/proto': typeof ProtoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proto/$slug': typeof ProtoSlugRoute
  '/spike/a': typeof SpikeARoute
  '/spike/b': typeof SpikeBRoute
  '/proto/': typeof ProtoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/proto/$slug' | '/spike/a' | '/spike/b' | '/proto/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proto/$slug' | '/spike/a' | '/spike/b' | '/proto'
  id: '__root__' | '/' | '/proto/$slug' | '/spike/a' | '/spike/b' | '/proto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtoSlugRoute: typeof ProtoSlugRoute
  SpikeARoute: typeof SpikeARoute
  SpikeBRoute: typeof SpikeBRoute
  ProtoIndexRoute: typeof ProtoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/': {
      id: '/proto/'
      path: '/proto'
      fullPath: '/proto/'
      preLoaderRoute: typeof ProtoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/$slug': {
      id: '/proto/$slug'
      path: '/proto/$slug'
      fullPath: '/proto/$slug'
      preLoaderRoute: typeof ProtoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/a': {
      id: '/spike/a'
      path: '/spike/a'
      fullPath: '/spike/a'
      preLoaderRoute: typeof SpikeARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spike/b': {
      id: '/spike/b'
      path: '/spike/b'
      fullPath: '/spike/b'
      preLoaderRoute: typeof SpikeBRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtoSlugRoute: ProtoSlugRoute,
  SpikeARoute: SpikeARoute,
  SpikeBRoute: SpikeBRoute,
  ProtoIndexRoute: ProtoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
